### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by helmarw** [wizjin/Argus#1]
first of all very nice work.
simple interface, fast, export option, works for me (iphone12maxpro)

few things you might want to look at:

1) export is ok, maybe an other option like text or html file, maybe nice
or at least write on the screen with the QR-code which account have been exported
2) icons would be nice to quicker identify, even if i have to add them manually (automatic would be even nicer or both)
3) some way to sort them (subfolders ?!)  
4) some way to rearrange/move them
5) search function

just a few ideas i made a fork, maybe ill find some time to get it to work myself and try to modify it ;)

anyway nice work!

PS: the name "Argus" is used quite a bit in the Appstore, you might want to think of an other name ?!

**Comment by wizjin** [comment]
Thank you so much for your suggestion.

1. Export  into text file. This feature will to be added in the next version.
2. My plan is to support [simple-icons](https://github.com/simple-icons/simple-icons) to add icon.
3. Sort item is a good idea. I will add this to TODO list.
4. I am looking for a suitable UI.
5. Good idea, I will think about how to implement.

By the way, I'm not good at naming. :(

Thank you very much. :)

PS: PR is always welcome.

**Comment by panosl** [comment]
@wizjin it would be really useful to create tickets for all TODO items on your list, so it'll be easier to manage, and people with suggestions, will see that those suggestions/features are already on your radar.
