### ISSUE TITLE
Explain how migration works

### ISSUE THREAD

**Issue by panosl** [wizjin/Argus#3]
This needs to be made explicit.

How does migration work? Is there some way to restore Argus data from a backup file?

Can I import data from another OTP app, ie OTP Auth: https://apps.apple.com/us/app/otp-auth/id659877384

**Comment by wizjin** [comment]
This app support otpauth-migration protocol.

You can export data into a qrcode, or import from a qrcode.

You can import from any another OTP app which support otpauth-migration format.
E.g. [Google Authenticato‪r‬](https://apps.apple.com/us/app/google-authenticator/id388497605)

Reference
- otpauth: https://github.com/google/google-authenticator/wiki/Key-Uri-Format
- otpauth-migration: https://github.com/google/google-authenticator-android/issues/118

If there are some other backup format document, I will plan to support them.

Thank you very much.
